Repository Programmers-Arena/ProgrammingProblemSolving, pull requests merged in 2022-10, with the labels that each got.

#10 Solved p1_insertAtPosition.cpp
  c++/p1_insertAtPosition.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, c++

#14 Solved p2_numberList.py
  python/p2_numberList.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, python

#11 updated python
  python/p1_insertAtPosition.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, python

#15 Solved cpp problem2
  c++/p2_numberGames.cpp
Labels: hacktoberfest, hacktoberfest2022, c++

#19 Solved cpp problem mergeCommonElements
  c++/p3_mergeCommonElements.cpp
Labels: hacktoberfest, hacktoberfest2022, c++

#22 Solved python problem
  python/p3_mergeCommonElements.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, python

#25 bg image addition and image resolution fix
  img/page-bg.svg
  index.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2022
